[package]
name = "sui_hypersfun"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.68.0" }

[addresses]
sui_hypersfun = "0x0"
sui = "0x2"

[dev-dependencies]

[dev-addresses]
